{ config, options, pkgs, pkgsLocal, lib, ... }:

let
  inherit (lib) mkIf mkOption mkEnableOption types;

  cfg = config.modules.x11.xsession;
in
{
  options.modules.x11.xsession = {
    enable = mkEnableOption "xsession";

    videoDrivers = mkOption {
      type = with types; str;
      description = "Video drivers to use. See services.xserver.videoDrivers";
    };
  };

  config = mkIf cfg.enable {
    environment.etc."profile.local".text = ''
      # /etc/profile.local: DO NOT EDIT -- autogenerated
      # just run X
      if [ -z "$DISPLAY" ] && [ $( tty ) == "/dev/tty1" ]; then
        exec startx
      fi
    '';

    services.xserver = {
      enable = true;
      videoDrivers = [ cfg.videoDrivers ];
      displayManager.startx.enable = true;
    };

    system.user.hm.xsession = {
      enable = true;
      # scriptPath = ".xinitrc";
    };
  };
}
